### PR TITLE
Experimental project structure

### PR DESCRIPTION
**Pull request by scohen**
Experimental project structure

There is only one commit in this pr, d8b96940ea93fc5b3c77a8b25e62454101bb30f0

This commit represents a new structure for the experimental project, and a path forward. With these changes the project now has:
   * A build option enabling the experimental server
   * Per-message routing for the experimental server. If enabled, it can
     either share messages with the existing server or take them over.
     Presently, the find references and formatting providers are
     implemented and "exclusive", meaning that they're handled solely by
     the experimental server if it's enabled.
   * A consistent interface for building providers.
   * A consistent way to convert LSP messages into data structures and
     back again. This conversion is handled automatically for providers.
   * A genserver-like interface for providers to implement
   * Data structures representing LSP messages that are simple to define
     and build.
   * Fast and efficient conversion between utf8 and utf16.
   * A separation between what a provider does and how it responds to
      messages. This allows the work that underpins providers to be tested
      independently from the language server.

This branch is designed to be able to be merged without affecting the rest of the project, but if this path looks good, I recommend the following course of action.

1. We should pause feature development and focus on porting existing features to the experimental server. There aren't that many existing providers, and that should happen fairly quickly. New feature development should take place in the `experimental` module from then on.  

2. We should also standardize on some type of source code modification, likely [https://github.com/doorgan/sourceror](sourceror). It's an excellent little library that has features that are missing from the elixir macro modules and will allow us to transform source code more readily than before. 

3. We should also focus on feature quality over quantity. The goals for this stage of the project would be completely eliminating crash bugs, increasing performance and correctness and usability of the existing features. If i may pick on two recently added features, Code actions are completely broken and automatic imports have severe usability issues that make them fairly worthless.  We should put together and publish a product roadmap for this. 

4. Once the experimental server has gained feature parity with the classic server, we should do a cutover release, at which point the project can start adding features again, with more rigor and confidence than was possible in the past. 

FYI, I can work on this pretty much full time until March.

### CODE REVIEW

**Comment by scohen** [comment]
@lukaszsamson This is ready to go. 
One possible controversial decision: I added `sourceror` as a dependency in order to get `AST -> source code ` consistency across elixir versions.

**Comment by robmckinnon** [comment]
> @lukaszsamson This is ready to go. One possible controversial decision: I added `sourceror` as a dependency in order to get `AST -> source code ` consistency across elixir versions.

Shall we bump `sourceror` to [v0.12.1](https://github.com/doorgan/sourceror/releases/tag/v0.12.1)? It has some non-backwards compatible changes, particularly the removal of "ended" zippers.

I've started to develop a `refactor.extract.function` code action that utilizes `sourceror`. I've already ported it to [v0.12.1](https://github.com/doorgan/sourceror/releases/tag/v0.12.1).

Shall I develop the `refactor.extract.function` code action in the Experimental project structure, and PR when ready?

**Comment by scohen** [comment]
> Shall we bump sourceror to [v0.12](https://github.com/doorgan/sourceror/releases)?

Yes, feel free to bump it

> Shall I develop the refactor.extract.function code action in the Experimental project structure

Go for it.

**Comment by robmckinnon** [comment]
> > Shall we bump sourceror to [v0.12](https://github.com/doorgan/sourceror/releases)?
> 
> Yes, feel free to bump it

I've opened a PR to bump sourceror version: https://github.com/elixir-lsp/elixir-ls/pull/841

**Pull request merged**
