### PR TITLE
Implementations provider

### PR DESCRIPTION
**Pull request by lukaszsamson**
It's ready now. I had to revert a few changes as they break formatter tests

### CODE REVIEW

**Review by axelson — APPROVED** [review]
Good changes :heart:

**Comment by lukaszsamson** [comment]
Looking into test failures

**Comment by axelson** [comment]
:+1: after the test failures are figured out we can merge this

**Comment by lukaszsamson** [comment]
For future reference the tests failed because on elixir < 1.11 the fixture modules were not loaded and somehow the are not a part of any application. There is a function `:code.all_available/0` but it is otp >= 23

**Comment by axelson** [comment]
Here are some screenshots showing off this change:

Peek definition:
PeekDefinition

Peek implementation:
PeekImplementations

**Comment by axelson** [comment]
Also peek implementations to find implementations of a protocol:

PeekImplementationsProtocol

And peek implementations to find implementations of a behaviour:

PeekImplementationBehaviour

**Pull request merged**
