### PR TITLE
Update readme and Emacs configuration docs

### PR DESCRIPTION
**Pull request by DaniruKun**
Mainly to reflect the addition of the new `elixir-ls` Brew formula.

- Remove duplicated sections from `readme`
- Add key info like install instructions in `readme`
- Add more Emacs install info in the docsite
- Add TOC to `readme`

### CODE REVIEW

**Comment by DaniruKun** [comment]
Also I think that the development guides in https://github.com/elixir-lsp/elixir-ls/tree/master/guides should probablly move into `docs` and be available in the docsite. Of course want to hear your comments about this idea.

**Comment by lukaszsamson** [comment]
Why are you removing features documentation (Debugger, Workspace symbols etc.)?

**Review by lukaszsamson — CHANGES_REQUESTED** [review]
Move Debugger and other features docs to appropriate place instead of removing it

**Comment by DaniruKun** [comment]
@lukaszsamson they are not removed, they have already been moved to the docsite. E.g. see https://elixir-lsp.github.io/elixir-ls/getting-started/vscode/#debugger and https://elixir-lsp.github.io/elixir-ls/features/

This is to keep the README clean and only have the most important info in it, and keep more detailed and searchable information on the docsite. This is pretty standard for other Language Server projects.

**Comment by lukaszsamson** [comment]
@DaniruKun can you resolve conflicts

**Comment by DaniruKun** [comment]
Done

**Comment by lukaszsamson** [comment]
Sorry I missed the update and the PR is once again out of date. Furthermore, the homebrew install is not supported

**Pull request closed without merging**
