### PR TITLE
Update ElixirSense

### LINKED ISSUE #68: Pull in latest ElixirSense changes
These PR's are definitely worth updating for:
* https://github.com/elixir-lsp/elixir_sense/pull/56
* https://github.com/elixir-lsp/elixir_sense/pull/57
* https://github.com/elixir-lsp/elixir_sense/pull/58

### PR DESCRIPTION
**Pull request by axelson**
Here are some of the key PR's that this brings in:

* https://github.com/elixir-lsp/elixir_sense/pull/56
* https://github.com/elixir-lsp/elixir_sense/pull/57
* https://github.com/elixir-lsp/elixir_sense/pull/58

Fixes #68

### CODE REVIEW

**Comment by victorolinasc** [comment]
I've had to do the patch below in order to get newer versions passing. Hope it helps :)

```elixir
   defp xref_at_cursor(text, line, character) do
-    env_at_cursor = line_environment(text, line)
+    {metadata, env_at_cursor} = line_environment(text, line)
     %{aliases: aliases} = env_at_cursor
 
     subject_at_cursor(text, line, character)
     # TODO: Don't call into here directly
     |> ElixirSense.Core.Source.split_module_and_func(aliases)
-    |> expand_mod_fun(env_at_cursor)
+    |> expand_mod_fun(metadata, env_at_cursor)
     |> add_arity(env_at_cursor)
     |> callers()
   end
 
   defp line_environment(text, line) do
     # TODO: Don't call into here directly
-    ElixirSense.Core.Parser.parse_string(text, true, true, line + 1)
-    |> ElixirSense.Core.Metadata.get_env(line + 1)
+    metadata = ElixirSense.Core.Parser.parse_string(text, true, true, line + 1)
+
+    {metadata, ElixirSense.Core.Metadata.get_env(metadata, line + 1)}
   end
 
   defp subject_at_cursor(text, line, character) do
@@ -43,11 +44,23 @@ defmodule ElixirLS.LanguageServer.Providers.References do
     ElixirSense.Core.Source.subject(text, line + 1, character + 1)
   end
 
-  defp expand_mod_fun({nil, nil}, _environment), do: nil
+  defp expand_mod_fun({nil, nil}, _metadata, _environment), do: nil
 
-  defp expand_mod_fun(mod_fun, %{imports: imports, aliases: aliases, module: module}) do
+  defp expand_mod_fun(mod_fun, metadata, %{
+         imports: imports,
+         aliases: aliases,
+         module: module
+       }) do
     # TODO: Don't call into here directly
-    mod_fun = ElixirSense.Core.Introspection.actual_mod_fun(mod_fun, imports, aliases, module)
+
+    mod_fun =
+      ElixirSense.Core.Introspection.actual_mod_fun(
+        mod_fun,
+        imports,
+        aliases,
+        module,
+        metadata.mods_funs
+      )
 

```

**Comment by axelson** [comment]
@victorolinasc thanks for the hint! Although this will probably be superseded by #82

**Comment by victorolinasc** [comment]
Nice :) This was a dirty hack to make it work locally.

**Comment by victorolinasc** [comment]
@axelson this can be closed now that #82 got merged, right?

**Comment by axelson** [comment]
Yes it can, thanks!

**Pull request closed without merging**
