### PR TITLE
Fix windows ci

### PR DESCRIPTION
**Pull request by scohen**
Changed paths in tests so that they're windows compatible.

Resubmitting this PR so that tests will run

### CODE REVIEW

**Comment by scohen** [comment]
@lukaszsamson I'm pretty stuck here until I can get actions to run. Not sure why they're not running.

**Comment by lukaszsamson** [comment]
Hasn’t it run the same commit on different branch?

**Comment by scohen** [comment]
Not that I can tell. I made changes and it hasn’t run them yet.

**Comment by lukaszsamson** [comment]
I’ve seen that once. Closing the PR and opening a new one helped. Otherwise we can add a manual workflow trigger

**Comment by scohen** [comment]
@lukaszsamson I did, this is a brand new PR.

**Comment by scohen** [comment]
@lukaszsamson did you do anything? I changed the base branch, and now CI is running.

**Comment by lukaszsamson** [comment]
I pushed your changes to my branch. Not sure what helped

**Comment by scohen** [comment]
@lukaszsamson I'm getting super frustrated with this.

Why do we need this check to see if an input applies? Shouldn't that be handled in the call to `formatter_for_file` ?

**Comment by lukaszsamson** [comment]
> I'm getting super frustrated with this.

I'll try to fix it on a windows machine

> Why do we need this check to see if an input applies? Shouldn't that be handled in the call to `formatter_for_file` ?

No idea, I've always felt that those `can_format` and `should_format` calls were fishy. @axelson Maybe you remember?

`formatter_for_file` is available only since elixir 1.13 and the formatter was there for much longer. We'll be dropping 1.12 support soon. I planned one last release before that happens

**Comment by scohen** [comment]
FWIW, i'm pretty sure the test failures are just test failures due to inconsistencies in the testing code. If we get paths from the system on windows, they should be consistent.

**Comment by lukaszsamson** [comment]
With those changes https://github.com/elixir-lsp/elixir-ls/pull/851/commits/32e70c153bfcb5a4c9436ff312e320fbe99c15f9 tests pass on windows. The takeaway is `document.path` uses native separators but `File.cwd!`, `project_path` and most if not all of elixir APIs return windows paths with unix separators

**Comment by lukaszsamson** [comment]
Superceded by https://github.com/elixir-lsp/elixir-ls/pull/851

**Pull request closed without merging**
