### PR TITLE
Add some basic installation instructions

### LINKED ISSUE #48: Better vim installation instructions
Hi there!

Thanks for the work on elixir-ls. I might be missing it, but I don't see any friendly details on how to get it installed. I found https://www.rockyourcode.com/developing-with-elixir-in-vim which worked for me with Vim and Ale, but curious if it makes sense to point folks to some more help getting things installed?

Thanks!

### PR DESCRIPTION
**Pull request by axelson**
In the future this could be expanded with explicit instructions instead of just links

Fixes #48

### CODE REVIEW

**Comment by axelson** [comment]
Yeah, we can probably go ahead and do that. Do you think that info belongs in the main Readme or should we start a new doc?

**Comment by asummers** [comment]
I think that's more a function of length. If it's able to fit in the README in a succinct enough way, then let's prefer that, but if it becomes involved, let's link out.

**Comment by victorolinasc** [comment]
I'll add my cents here :)

I think the whole installation story of elixir-ls can be a lot better. I think we should experiment with options.

Ideally, we wouldn't need to deal with PATH variables. `elixir-ls` is an elixir project so we could handle it with elixir tooling. I was experimenting with making it an archive so that we could only:

```elixir
mix archive.install lsp 1.0.0-otp-21
```

And then, to start the server we would only need: `mix lsp --options`.

Or maybe we could turn it into a dependency with test only scope that would provide a simple mix task like this one:

```elixir
defmodule Mix.Tasks.Lsp do
  @moduledoc """
  Runs the lsp server.
  """
  use Mix.Task

  alias ElixirLS.LanguageServer.CLI

  @shortdoc "Runs the LSP server"
  def run(_) do
    CLI.main()
  end
end
```

This would simplify some custom approaches of the project. 

What do you think?

**Comment by victorolinasc** [comment]
I was just enlighted that an escript is also "installable"... that would be very easy to provide IMHO. I'll test it locally.

**Comment by axelson** [comment]
Replaced by #326

**Pull request closed without merging**
