### PR TITLE
add additional extensions, clean

### PR DESCRIPTION
**Pull request by vanjabucic**
Linked issue: #567

### CODE REVIEW

**Comment by lukaszsamson** [comment]
@vanjabucic please see into the failed tests

**Comment by lukaszsamson** [comment]
Looks good. Can you add some tests?

**Comment by lukaszsamson** [comment]
@vanjabucic are you still interested in finishing this PR?

**Comment by vanjabucic** [comment]
Not sure how to write tests for such a minor code shuffle ...

**Comment by lukaszsamson** [comment]
> Not sure how to write tests for such a minor code shuffle ...

It's a new feature off by default. This means not many people will be actively testing it and having no test coverage means more maintenance pressure for the team.
There are tests for some init scenarios. Please add another one what makes sure that additional extensions are properly parsed and added to server state.

**Comment by vanjabucic** [comment]
The way extension handling is/has been done means that the state remains unaffected. Extensions are hard-coded, sent to server via RPC, and checked against inline. Extensions are never parsed and added to the server state. Could not find a way to test server state because of that. (should extension list be carried in the server state? that can be done if desired)

What I did was to add a test that verifies that a non-standard-extension file will trigger a build when changed. That should cover it when combined with other existing tests that work on hard-coded file extensions.

Take a look and tell me if that is enough or on the right track.

**Comment by lukaszsamson** [comment]
Thanks

**Pull request merged**
