### PR TITLE
Describe the reasoning behind the fork

### LINKED ISSUE #22: What's this project's goal?
Hi, I just stumbled upon this repo and wonder two things:
- What's this project its goal, or how is it different from Jake Becker's version?
- Why or when should I use this project instead of Jake Becker's version

KR,
Edward

### PR DESCRIPTION
**Pull request by axelson**
Fixes #22

### CODE REVIEW

**Comment by Trevoke** [comment]
I know that we're trying to be open about combining efforts, but putting the message about wanting to join forces with Jake there could be interpreted as passive-aggressive. We just have to keep reaching out to him.

**Comment by axelson** [comment]
@Trevoke Very good point. Updated to remove that sentence.

**Comment by jsmestad** [comment]
@axelson I read the note on the fork and walked away wanting answers to a few more questions in that section:

* Will upstream contributions be maintained in this version?
* Are there additional features of this branch over the other?
* Am I losing any features?
* You describe an open governance model, but do not mention how to get involved or where to help. Is the conversation in Slack? I'd mention that.

**Comment by axelson** [comment]
@jsmestad thanks, that's good feedback

> Will upstream contributions be maintained in this version?

yes

> Are there additional features of this branch over the other?

Previously there were more, but now both are near feature parity

> Am I losing any features?

Nothing currently

> You describe an open governance model, but do not mention how to get involved or where to help. Is the conversation in Slack? I'd mention that.

Yeah that is a good point. The conversion is in Elixir Slack in the #language-server channel. Would be good to add some more info about how to get involved or help in the Contributing doc

**Pull request merged**
